<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc 3.10.1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <meta name="author" content="Hua Huang" />
  <meta name="dcterms.date" content="2026-05-01" />
  <title>ModuleViz: CD8 T Cell Exhaustion Published Data</title>
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    /* The extra [class] is a hack that increases specificity enough to
       override a similar rule in reveal.js */
    ul.task-list[class]{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      font-size: inherit;
      width: 0.8em;
      margin: 0 0.8em 0.2em -1.6em;
      vertical-align: middle;
    }
    .display.math{display: block; text-align: center; margin: 0.5rem auto;}
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      {   }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span.al { color: #ff0000; font-weight: bold; } /* Alert */
    code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
    code span.at { color: #7d9029; } /* Attribute */
    code span.bn { color: #40a070; } /* BaseN */
    code span.bu { color: #008000; } /* BuiltIn */
    code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #4070a0; } /* Char */
    code span.cn { color: #880000; } /* Constant */
    code span.co { color: #60a0b0; font-style: italic; } /* Comment */
    code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
    code span.do { color: #ba2121; font-style: italic; } /* Documentation */
    code span.dt { color: #902000; } /* DataType */
    code span.dv { color: #40a070; } /* DecVal */
    code span.er { color: #ff0000; font-weight: bold; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #40a070; } /* Float */
    code span.fu { color: #06287e; } /* Function */
    code span.im { color: #008000; font-weight: bold; } /* Import */
    code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
    code span.kw { color: #007020; font-weight: bold; } /* Keyword */
    code span.op { color: #666666; } /* Operator */
    code span.ot { color: #007020; } /* Other */
    code span.pp { color: #bc7a00; } /* Preprocessor */
    code span.sc { color: #4070a0; } /* SpecialChar */
    code span.ss { color: #bb6688; } /* SpecialString */
    code span.st { color: #4070a0; } /* String */
    code span.va { color: #19177c; } /* Variable */
    code span.vs { color: #4070a0; } /* VerbatimString */
    code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../biocstyle.css" />
</head>
<body>
<header id="title-block-header">
<h1 class="title">ModuleViz: CD8 T Cell Exhaustion Published Data</h1>
<p class="author">Hua Huang</p>
<p class="date">2026-05-01</p>
<div class="abstract">
<div class="abstract-title">Abstract</div>
<p>This vignette demonstrates a reproducible ModuleViz workflow using
published RNA-seq and CUT&amp;RUN data from memory and exhausted CD8 T
cells. RNA-seq data define temporal modules along an ordered
differentiation axis, and H3K27ac CUT&amp;RUN signal is aligned to those
modules by gene.</p>
</div>
</header>
<nav id="TOC" role="doc-toc">
<ul>
<li><a href="#introduction" id="toc-introduction"><span
class="toc-section-number">1</span> Introduction</a></li>
<li><a href="#requirements" id="toc-requirements"><span
class="toc-section-number">2</span> Requirements</a></li>
<li><a href="#read-the-rna-seq-matrix"
id="toc-read-the-rna-seq-matrix"><span
class="toc-section-number">3</span> Read The RNA-seq Matrix</a></li>
<li><a href="#build-the-sample-metadata"
id="toc-build-the-sample-metadata"><span
class="toc-section-number">4</span> Build The Sample Metadata</a></li>
<li><a href="#select-differentially-expressed-genes"
id="toc-select-differentially-expressed-genes"><span
class="toc-section-number">5</span> Select Differentially Expressed
Genes</a></li>
<li><a href="#choose-the-number-of-modules"
id="toc-choose-the-number-of-modules"><span
class="toc-section-number">6</span> Choose The Number Of
Modules</a></li>
<li><a href="#cluster-into-temporal-modules"
id="toc-cluster-into-temporal-modules"><span
class="toc-section-number">7</span> Cluster Into Temporal
Modules</a></li>
<li><a href="#check-the-modules-against-known-biology"
id="toc-check-the-modules-against-known-biology"><span
class="toc-section-number">8</span> Check The Modules Against Known
Biology</a></li>
<li><a href="#draw-the-heatmap" id="toc-draw-the-heatmap"><span
class="toc-section-number">9</span> Draw The Heatmap</a></li>
<li><a href="#plot-module-trajectories"
id="toc-plot-module-trajectories"><span
class="toc-section-number">10</span> Plot Module Trajectories</a></li>
<li><a href="#check-module-coherence"
id="toc-check-module-coherence"><span
class="toc-section-number">11</span> Check Module Coherence</a></li>
<li><a href="#export-the-tables" id="toc-export-the-tables"><span
class="toc-section-number">12</span> Export The Tables</a></li>
<li><a href="#add-the-cutrun-layer" id="toc-add-the-cutrun-layer"><span
class="toc-section-number">13</span> Add The CUT&amp;RUN Layer</a></li>
<li><a href="#reproducing-everything"
id="toc-reproducing-everything"><span
class="toc-section-number">14</span> Reproducing Everything</a></li>
<li><a href="#adapting-this-to-your-own-data"
id="toc-adapting-this-to-your-own-data"><span
class="toc-section-number">15</span> Adapting This To Your Own
Data</a></li>
<li><a href="#citation" id="toc-citation"><span
class="toc-section-number">16</span> Citation</a></li>
<li><a href="#session-information" id="toc-session-information"><span
class="toc-section-number">17</span> Session Information</a></li>
</ul>
</nav>
<h1 data-number="1" id="introduction"><span
class="header-section-number">1</span> Introduction</h1>
<p><a href="https://bioconductor.org/packages/ModuleViz/">ModuleViz</a>
can be used with an ordered biological axis even when the axis is not
clock time. This vignette demonstrates that workflow on published CD8 T
cell differentiation data.</p>
<p>The other vignette uses the bundled synthetic dataset so it runs
offline. This one is the opposite: it walks through a complete,
published, real analysis end to end, on data anyone can download.</p>
<p>We use two GEO series from the same study of histone modifications in
memory and exhausted CD8 T cells (PubMed <a
href="https://pubmed.ncbi.nlm.nih.gov/40389726/">40389726</a>):</p>
<table>
<colgroup>
<col style="width: 25%" />
<col style="width: 25%" />
<col style="width: 25%" />
<col style="width: 25%" />
</colgroup>
<thead>
<tr>
<th>Accession</th>
<th>Assay</th>
<th>Samples</th>
<th>What we use it for</th>
</tr>
</thead>
<tbody>
<tr>
<td><a
href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE285248">GSE285248</a></td>
<td>RNA-seq</td>
<td>16</td>
<td>Defines the temporal modules</td>
</tr>
<tr>
<td><a
href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE285245">GSE285245</a></td>
<td>CUT&amp;RUN (H3K27ac, H3K27me3)</td>
<td>86</td>
<td>Chromatin layer aligned to those modules</td>
</tr>
</tbody>
</table>
<p><strong>The experiment.</strong> Naive P14 CD8 T cells were
transferred into recipient mice infected with LCMV Armstrong, which
resolves and yields <strong>memory</strong> cells (harvested day 30), or
LCMV Clone 13, which persists and yields <strong>exhausted</strong>
cells (harvested day 32). Spleens were profiled by RNA-seq and by
CUT&amp;RUN for activating (H3K27ac, H3K4me3) and repressive (H3K27me3,
H3K9me3) marks.</p>
<p><strong>The trajectory.</strong> <code>ModuleViz</code> was built for
time courses, but nothing in it requires the ordering variable to be
wall-clock time. Here the ordered axis is a <em>differentiation</em>
axis:</p>
<pre><code>TN (naive)  -&gt;  TMEM (memory)  -&gt;  TEX (exhausted)</code></pre>
<p>Any ordinal sample axis works the same way: differentiation stages,
disease grades, dose levels, or developmental stages.</p>
<blockquote>
<p><strong>Chunks in this vignette are not evaluated at build
time</strong>, because they download data from the NCBI FTP server.
Every chunk is runnable as written — copy them in order, or run the
whole thing at once with
<code>Rscript examples/validate_real_data.R</code> from the package
root, which executes this exact analysis plus 114 correctness
assertions.</p>
</blockquote>
<h1 data-number="2" id="requirements"><span
class="header-section-number">2</span> Requirements</h1>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ModuleViz)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span></code></pre></div>
<p>Only the small processed count matrices are downloaded, about 4.7 MB
in total. The multi-gigabyte <code>_RAW.tar</code> archives on GEO are
never touched.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>cache_dir <span class="ot">&lt;-</span> <span class="st">&quot;geo_cache&quot;</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dir.create</span>(cache_dir, <span class="at">recursive =</span> <span class="cn">TRUE</span>, <span class="at">showWarnings =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>GEO <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">rna      =</span> <span class="fu">list</span>(<span class="at">gse =</span> <span class="st">&quot;GSE285248&quot;</span>, <span class="at">file =</span> <span class="st">&quot;GSE285248_NormRC_filter_wanno.txt.gz&quot;</span>),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">h3k27ac  =</span> <span class="fu">list</span>(<span class="at">gse =</span> <span class="st">&quot;GSE285245&quot;</span>, <span class="at">file =</span> <span class="st">&quot;GSE285245_NormRC_H3K27ac_wID.txt.gz&quot;</span>),</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">h3k27me3 =</span> <span class="fu">list</span>(<span class="at">gse =</span> <span class="st">&quot;GSE285245&quot;</span>, <span class="at">file =</span> <span class="st">&quot;GSE285245_NormRC_H3K27me3_wID.txt.gz&quot;</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>geo_path <span class="ot">&lt;-</span> <span class="cf">function</span>(entry) {</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  dest <span class="ot">&lt;-</span> <span class="fu">file.path</span>(cache_dir, entry<span class="sc">$</span>file)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">file.exists</span>(dest)) {</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    url <span class="ot">&lt;-</span> <span class="fu">sprintf</span>(<span class="st">&quot;https://ftp.ncbi.nlm.nih.gov/geo/series/%snnn/%s/suppl/%s&quot;</span>,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">substr</span>(entry<span class="sc">$</span>gse, <span class="dv">1</span>, <span class="dv">6</span>), entry<span class="sc">$</span>gse, entry<span class="sc">$</span>file)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    utils<span class="sc">::</span><span class="fu">download.file</span>(url, dest, <span class="at">mode =</span> <span class="st">&quot;wb&quot;</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>  dest</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>paths <span class="ot">&lt;-</span> <span class="fu">lapply</span>(GEO, geo_path)</span></code></pre></div>
<h1 data-number="3" id="read-the-rna-seq-matrix"><span
class="header-section-number">3</span> Read The RNA-seq Matrix</h1>
<p>The RNA table carries six annotation columns (<code>Chr</code>,
<code>Start</code>, <code>End</code>, <code>Geneid</code>,
<code>Gene.Name</code>, <code>Strand</code>) followed by the 16 sample
columns. A handful of gene symbols appear under more than one Ensembl
ID, so we keep the most highly expressed copy of each symbol and use
symbols as rownames.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>rna_raw  <span class="ot">&lt;-</span> <span class="fu">fread</span>(paths<span class="sc">$</span>rna)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>rna_cols <span class="ot">&lt;-</span> <span class="fu">grep</span>(<span class="st">&quot;_RNA_&quot;</span>, <span class="fu">names</span>(rna_raw), <span class="at">value =</span> <span class="cn">TRUE</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>rna_raw[, .mean_expr <span class="sc">:=</span> <span class="fu">rowMeans</span>(<span class="fu">as.matrix</span>(.SD)), .SDcols <span class="ot">=</span> rna_cols]</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">setorder</span>(rna_raw, Gene.Name, <span class="sc">-</span>.mean_expr)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>rna_uniq <span class="ot">&lt;-</span> rna_raw[<span class="sc">!</span><span class="fu">duplicated</span>(Gene.Name)]</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>rna_mat <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(rna_uniq[, ..rna_cols])</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(rna_mat) <span class="ot">&lt;-</span> rna_uniq<span class="sc">$</span>Gene.Name</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(rna_mat)</span></code></pre></div>
<pre><code>#&gt; [1] 16429    16</code></pre>
<h1 data-number="4" id="build-the-sample-metadata"><span
class="header-section-number">4</span> Build The Sample Metadata</h1>
<p><code>ModuleViz</code> needs one row per sample with a sample ID and
a <strong>numeric</strong> ordering column. The GEO column names encode
everything we need in the pattern
<code>&lt;Infection&gt;_P14_Day&lt;d&gt;_&lt;assay&gt;_Rep&lt;n&gt;_S&lt;n&gt;</code>,
so the metadata can be parsed straight out of them. Writing this as a
function pays off later, because the CUT&amp;RUN tables follow exactly
the same naming scheme.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>make_meta <span class="ot">&lt;-</span> <span class="cf">function</span>(cols, assay) {</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  infection <span class="ot">&lt;-</span> <span class="fu">sub</span>(<span class="st">&quot;_P14_.*&quot;</span>, <span class="st">&quot;&quot;</span>, cols)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  day       <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(<span class="fu">sub</span>(<span class="st">&quot;.*_Day([0-9]+)_.*&quot;</span>, <span class="st">&quot;</span><span class="sc">\\</span><span class="st">1&quot;</span>, cols))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  state     <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">Naive =</span> <span class="st">&quot;TN&quot;</span>, <span class="at">Arm =</span> <span class="st">&quot;TMEM&quot;</span>, <span class="at">Cl13 =</span> <span class="st">&quot;TEX&quot;</span>)[infection]</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.table</span>(</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">SampleID   =</span> cols,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">State      =</span> <span class="fu">factor</span>(state, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;TN&quot;</span>, <span class="st">&quot;TMEM&quot;</span>, <span class="st">&quot;TEX&quot;</span>)),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># the ordered differentiation axis handed to time_col</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">StateOrder =</span> <span class="fu">unname</span>(<span class="fu">c</span>(<span class="at">TN =</span> <span class="dv">1</span>, <span class="at">TMEM =</span> <span class="dv">2</span>, <span class="at">TEX =</span> <span class="dv">3</span>)[state]),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># naive cells are the pre-infection baseline, so they sit at day 0</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">Day        =</span> <span class="fu">ifelse</span>(infection <span class="sc">==</span> <span class="st">&quot;Naive&quot;</span>, <span class="dv">0</span><span class="dt">L</span>, day),</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">Replicate  =</span> <span class="fu">as.integer</span>(<span class="fu">sub</span>(<span class="st">&quot;.*_Rep([0-9]+)_.*&quot;</span>, <span class="st">&quot;</span><span class="sc">\\</span><span class="st">1&quot;</span>, cols)),</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">Assay      =</span> assay</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>rna_meta <span class="ot">&lt;-</span> <span class="fu">make_meta</span>(rna_cols, <span class="st">&quot;RNA&quot;</span>)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>rna_meta[, .N, by <span class="ot">=</span> .(State, Day)]</span></code></pre></div>
<pre><code>#&gt;     State   Day     N
#&gt;    &lt;fctr&gt; &lt;int&gt; &lt;int&gt;
#&gt; 1:     TN     0     8
#&gt; 2:   TMEM    30     4
#&gt; 3:    TEX    32     4</code></pre>
<p><code>StateOrder</code> is the key column: it is what
<code>time_col</code> will point at, and it is what makes the modules
come out ordered naive-high through exhaustion-high.</p>
<p>Note that there are <strong>eight</strong> naive samples, not four.
Naive cells were profiled twice, once alongside each infection, so they
serve as the day-matched baseline for both arms. That imbalance is fine
— nothing in <code>ModuleViz</code> requires equal group sizes.</p>
<h1 data-number="5" id="select-differentially-expressed-genes"><span
class="header-section-number">5</span> Select Differentially Expressed
Genes</h1>
<p>Real analyses do not cluster the whole transcriptome. Clustering
16,429 genes would bury the interesting structure under thousands of
flat, uninformative profiles. We select the genes that actually move
across the three states.</p>
<p>A vectorised one-way ANOVA across <code>TN</code> / <code>TMEM</code>
/ <code>TEX</code> is fast and needs no extra packages. If you already
have <code>DESeq2</code> or <code>edgeR</code> results for this
comparison, substitute them here — all that matters downstream is a set
of gene IDs and, optionally, a ranking statistic.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>log_rna <span class="ot">&lt;-</span> <span class="fu">log2</span>(rna_mat <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>deg_anova <span class="ot">&lt;-</span> <span class="cf">function</span>(x, grp) {</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  grp <span class="ot">&lt;-</span> <span class="fu">factor</span>(grp)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">ncol</span>(x); k <span class="ot">&lt;-</span> <span class="fu">nlevels</span>(grp)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  grand <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(x)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  ssb <span class="ot">&lt;-</span> <span class="dv">0</span>; ssw <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (g <span class="cf">in</span> <span class="fu">levels</span>(grp)) {</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    cols <span class="ot">&lt;-</span> <span class="fu">which</span>(grp <span class="sc">==</span> g)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    mg   <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(x[, cols, <span class="at">drop =</span> <span class="cn">FALSE</span>])</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    ssb  <span class="ot">&lt;-</span> ssb <span class="sc">+</span> <span class="fu">length</span>(cols) <span class="sc">*</span> (mg <span class="sc">-</span> grand)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    ssw  <span class="ot">&lt;-</span> ssw <span class="sc">+</span> <span class="fu">rowSums</span>((x[, cols, <span class="at">drop =</span> <span class="cn">FALSE</span>] <span class="sc">-</span> mg)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  df1 <span class="ot">&lt;-</span> k <span class="sc">-</span> <span class="dv">1</span>; df2 <span class="ot">&lt;-</span> n <span class="sc">-</span> k</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  Fstat <span class="ot">&lt;-</span> (ssb <span class="sc">/</span> df1) <span class="sc">/</span> (ssw <span class="sc">/</span> df2)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  Fstat[<span class="sc">!</span><span class="fu">is.finite</span>(Fstat)] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.table</span>(</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">ID     =</span> <span class="fu">rownames</span>(x),</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">Fstat  =</span> Fstat,</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">pvalue =</span> stats<span class="sc">::</span><span class="fu">pf</span>(Fstat, df1, df2, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>),</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">padj   =</span> stats<span class="sc">::</span><span class="fu">p.adjust</span>(stats<span class="sc">::</span><span class="fu">pf</span>(Fstat, df1, df2, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>),</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>                             <span class="at">method =</span> <span class="st">&quot;BH&quot;</span>)</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>state_of <span class="ot">&lt;-</span> rna_meta<span class="sc">$</span>State[<span class="fu">match</span>(<span class="fu">colnames</span>(log_rna), rna_meta<span class="sc">$</span>SampleID)]</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>deg <span class="ot">&lt;-</span> <span class="fu">deg_anova</span>(log_rna, state_of)</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>mean_by <span class="ot">&lt;-</span> <span class="cf">function</span>(s) <span class="fu">rowMeans</span>(log_rna[, state_of <span class="sc">==</span> s, <span class="at">drop =</span> <span class="cn">FALSE</span>])</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>deg[, <span class="st">`</span><span class="at">:=</span><span class="st">`</span>(</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">log2FC_TMEM_vs_TN  =</span> <span class="fu">mean_by</span>(<span class="st">&quot;TMEM&quot;</span>) <span class="sc">-</span> <span class="fu">mean_by</span>(<span class="st">&quot;TN&quot;</span>),</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">log2FC_TEX_vs_TN   =</span> <span class="fu">mean_by</span>(<span class="st">&quot;TEX&quot;</span>)  <span class="sc">-</span> <span class="fu">mean_by</span>(<span class="st">&quot;TN&quot;</span>),</span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">log2FC_TEX_vs_TMEM =</span> <span class="fu">mean_by</span>(<span class="st">&quot;TEX&quot;</span>)  <span class="sc">-</span> <span class="fu">mean_by</span>(<span class="st">&quot;TMEM&quot;</span>),</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>  <span class="at">baseMean           =</span> <span class="fu">rowMeans</span>(rna_mat)</span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a>)]</span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>deg[, maxAbsLFC <span class="sc">:=</span> <span class="fu">pmax</span>(<span class="fu">abs</span>(log2FC_TMEM_vs_TN), <span class="fu">abs</span>(log2FC_TEX_vs_TN),</span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">abs</span>(log2FC_TEX_vs_TMEM))]</span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a>sig <span class="ot">&lt;-</span> deg[padj <span class="sc">&lt;</span> <span class="fl">0.01</span> <span class="sc">&amp;</span> maxAbsLFC <span class="sc">&gt;=</span> <span class="dv">1</span> <span class="sc">&amp;</span> baseMean <span class="sc">&gt;=</span> <span class="dv">10</span>]</span>
<span id="cb8-40"><a href="#cb8-40" aria-hidden="true" tabindex="-1"></a><span class="fu">setorder</span>(sig, <span class="sc">-</span>Fstat)</span>
<span id="cb8-41"><a href="#cb8-41" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(sig)</span></code></pre></div>
<pre><code>#&gt; [1] 4176</code></pre>
<p>4,176 genes pass. We keep the top 3,000 by ANOVA <em>F</em> so the
vignette runs quickly; raise or drop the cap freely.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>sig <span class="ot">&lt;-</span> sig[<span class="fu">seq_len</span>(<span class="fu">min</span>(<span class="dv">3000</span>, <span class="fu">nrow</span>(sig)))]</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Cluster on the log scale: z-scoring raw counts lets a few high-count</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># outliers dominate the distance metric.</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>deg_mat <span class="ot">&lt;-</span> <span class="fu">log2</span>(rna_mat[sig<span class="sc">$</span>ID, , <span class="at">drop =</span> <span class="cn">FALSE</span>] <span class="sc">+</span> <span class="dv">1</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sig<span class="sc">$</span>ID, <span class="dv">12</span>)</span></code></pre></div>
<pre><code>#&gt;  [1] &quot;Pik3ap1&quot; &quot;Myo1f&quot;   &quot;Chsy1&quot;   &quot;Gnptab&quot;  &quot;Ccr9&quot;    &quot;Satb1&quot;
#&gt;  [7] &quot;Rapgef6&quot; &quot;Il6ra&quot;   &quot;Sytl2&quot;   &quot;Ccr5&quot;    &quot;Tox&quot;     &quot;Fam169b&quot;</code></pre>
<p><code>Tox</code>, the master transcription factor of CD8 T cell
exhaustion, is already in the top 12 — a good sign that the selection is
picking up real biology.</p>
<h1 data-number="6" id="choose-the-number-of-modules"><span
class="header-section-number">6</span> Choose The Number Of Modules</h1>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">zscore_rows</span>(deg_mat)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>K <span class="ot">&lt;-</span> <span class="dv">6</span>   <span class="co"># see the note below</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>diag <span class="ot">&lt;-</span> <span class="fu">choose_k</span>(z, <span class="at">k_range =</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">12</span>, <span class="at">method =</span> <span class="st">&quot;kmeans&quot;</span>,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">file =</span> <span class="st">&quot;choose_k_elbow.pdf&quot;</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>diag</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="fu">attr</span>(diag, <span class="st">&quot;suggested_k&quot;</span>)</span></code></pre></div>
<pre><code>#&gt;         k tot_withinss mean_silhouette elbow_k
#&gt;  1:     2    10243.402       0.6761535       5
#&gt;  2:     3     7723.609       0.5215970       5
#&gt;  3:     4     6094.619       0.3693580       5
#&gt;  4:     5     5088.006       0.3522561       5
#&gt;  5:     6     4378.953       0.3252019       5
#&gt;  ...
#&gt; [1] 5</code></pre>
<p>The elbow lands at k = 5, but we use <strong>k = 6</strong>. This is
worth being explicit about, because it is the most common judgement call
in this workflow.</p>
<p>At k = 5 there is <strong>no memory-peaking module at all</strong>:
the TMEM-specific programme is absorbed into its neighbours, so the
modules run naive -&gt; naive -&gt; naive -&gt; exhausted -&gt;
exhausted. Since memory-versus-exhaustion is the comparison this study
exists to make, k = 5 would hide the result. At k = 6 a module with a
clear TMEM peak appears (Cluster4 below), and every module still has a
stability above 0.9.</p>
<p>The elbow is a heuristic; a k that merges two biologically distinct
programmes is worse than one that splits a module in two. If you want
the figure itself to record the k you settled on,
<code>choose_k(..., chosen_k = K)</code> draws it as a solid line beside
the dashed elbow, and <code>annotate_k = FALSE</code> strips both
markers for a bare curve.</p>
<h1 data-number="7" id="cluster-into-temporal-modules"><span
class="header-section-number">7</span> Cluster Into Temporal
Modules</h1>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>obj <span class="ot">&lt;-</span> <span class="fu">longitudinal_cluster</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  deg_mat, rna_meta,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sample_col =</span> <span class="st">&quot;SampleID&quot;</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">time_col   =</span> <span class="st">&quot;StateOrder&quot;</span>,   <span class="co"># the ordered differentiation axis</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">k          =</span> K,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">method     =</span> <span class="st">&quot;kmeans&quot;</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">stability  =</span> <span class="cn">TRUE</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">n_resample =</span> <span class="dv">20</span>,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed       =</span> <span class="dv">1</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>obj</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>obj<span class="sc">$</span>stability</span></code></pre></div>
<pre><code>#&gt; &lt;longi&gt;  3000 features x 16 samples,  6 modules (kmeans)
#&gt;   stability (mean Jaccard): 0.90 - 0.97
#&gt;     Cluster MeanJaccard     N
#&gt; 1: Cluster1       0.958   388
#&gt; 2: Cluster2       0.975   776
#&gt; 3: Cluster3       0.972   158
#&gt; 4: Cluster4       0.901   243
#&gt; 5: Cluster5       0.958  1019
#&gt; 6: Cluster6       0.968   416</code></pre>
<p>Every module has a mean Jaccard above 0.9 under resampling, so all
six are reproducible. Values below roughly 0.6 would mean a module is an
artefact of one particular clustering run and should not be
interpreted.</p>
<p>Modules are automatically renumbered so that <code>Cluster1</code>
peaks earliest and <code>Cluster6</code> peaks latest:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>cent <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(obj<span class="sc">$</span>centroids[, <span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(cent) <span class="ot">&lt;-</span> obj<span class="sc">$</span>centroids<span class="sc">$</span>Cluster</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(cent) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;TN&quot;</span>, <span class="st">&quot;TMEM&quot;</span>, <span class="st">&quot;TEX&quot;</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(cent, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>#&gt;            TN  TMEM   TEX
#&gt; Cluster1  0.74 -0.01 -1.48   &lt;- naive-high, lost on activation
#&gt; Cluster2  0.92 -0.87 -0.98   &lt;- naive-specific
#&gt; Cluster3  0.53 -1.53  0.46   &lt;- down in memory, partly restored in exhaustion
#&gt; Cluster4 -0.83  1.31  0.34   &lt;- memory-specific
#&gt; Cluster5 -0.92  0.69  1.15   &lt;- shared effector, highest in exhaustion
#&gt; Cluster6 -0.65 -0.26  1.55   &lt;- exhaustion-specific</code></pre>
<h1 data-number="8" id="check-the-modules-against-known-biology"><span
class="header-section-number">8</span> Check The Modules Against Known
Biology</h1>
<p>This is the step worth doing before any figure goes into a paper.
Canonical markers should land where the biology says they should.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>module_of <span class="ot">&lt;-</span> <span class="fu">setNames</span>(<span class="fu">as.character</span>(obj<span class="sc">$</span>cluster), <span class="fu">rownames</span>(obj<span class="sc">$</span>z))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>TEX_MARKERS <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Pdcd1&quot;</span>, <span class="st">&quot;Tox&quot;</span>, <span class="st">&quot;Havcr2&quot;</span>, <span class="st">&quot;Lag3&quot;</span>, <span class="st">&quot;Entpd1&quot;</span>, <span class="st">&quot;Cd101&quot;</span>, <span class="st">&quot;Cd160&quot;</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>TN_MARKERS  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Sell&quot;</span>, <span class="st">&quot;Ccr7&quot;</span>, <span class="st">&quot;Lef1&quot;</span>, <span class="st">&quot;Tcf7&quot;</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="fu">data.table</span>(<span class="at">Gene =</span> TEX_MARKERS, <span class="at">Module =</span> module_of[TEX_MARKERS])</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="fu">data.table</span>(<span class="at">Gene =</span> TN_MARKERS,  <span class="at">Module =</span> module_of[TN_MARKERS])</span></code></pre></div>
<pre><code>#&gt;      Gene   Module          #&gt;      Gene   Module
#&gt; 1:  Pdcd1 Cluster6          #&gt; 1:   Sell Cluster2
#&gt; 2:    Tox Cluster6          #&gt; 2:   Ccr7 Cluster2
#&gt; 3: Havcr2 Cluster5          #&gt; 3:   Lef1 Cluster1
#&gt; 4:   Lag3 Cluster6          #&gt; 4:   Tcf7 Cluster1
#&gt; 5: Entpd1 Cluster5
#&gt; 6:  Cd101 Cluster6
#&gt; 7:  Cd160 Cluster5</code></pre>
<p>Every inhibitory-receptor and exhaustion gene falls in Cluster5 or
Cluster6, the two exhaustion-peaking modules. Every naive/stemness gene
falls in Cluster1 or Cluster2, the naive-peaking modules. The clustering
recovered the expected programme without being told anything about
it.</p>
<h1 data-number="9" id="draw-the-heatmap"><span
class="header-section-number">9</span> Draw The Heatmap</h1>
<p>Three palettes are in play, and each is chosen for its job:</p>
<ul>
<li><code>cluster_palette</code> — a <strong>qualitative</strong>
palette for module identity (<code>"paired"</code>, <code>"set2"</code>,
<code>"set3"</code>, <code>"okabe_ito"</code>, …).</li>
<li><code>annotation_palette</code> — a qualitative palette for
categorical metadata bars. <code>"set2"</code> is the default; use
<code>"set3"</code> beyond eight levels.</li>
<li><code>zscore_palette</code> — a <strong>continuous</strong> scale
for the matrix body: <code>"viridis"</code> (perceptually uniform and
colour-blind safe) or <code>"rdbu"</code> (diverging). This walkthrough
uses one scheme throughout; change the single argument to swap it.</li>
</ul>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>rank_tab <span class="ot">&lt;-</span> sig[, .(ID, <span class="at">value =</span> <span class="sc">-</span><span class="fu">log10</span>(<span class="fu">pmax</span>(padj, .Machine<span class="sc">$</span>double.xmin)))]</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">longitudinal_heatmap</span>(</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  obj,</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">annotation_cols    =</span> <span class="fu">c</span>(<span class="st">&quot;State&quot;</span>, <span class="st">&quot;Day&quot;</span>),</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">rank_table         =</span> rank_tab,   <span class="co"># label the most significant genes per module</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">id_field           =</span> <span class="st">&quot;ID&quot;</span>,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">value_field        =</span> <span class="st">&quot;value&quot;</span>,</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">top_n_label        =</span> <span class="dv">3</span>,</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">zscore_palette     =</span> <span class="st">&quot;viridis&quot;</span>,  <span class="co"># &lt;- &quot;rdbu&quot; for the diverging alternative</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">cluster_palette    =</span> <span class="st">&quot;paired&quot;</span>,</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">annotation_palette =</span> <span class="st">&quot;set2&quot;</span>,</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># the GEO sample IDs are long and the State bar already says what each</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># column is, so suppress them and scale the remaining text up for print</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_column_names        =</span> <span class="cn">FALSE</span>,</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">label_fontsize           =</span> <span class="dv">13</span>,</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">row_title_fontsize       =</span> <span class="dv">13</span>,</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">annotation_name_fontsize =</span> <span class="dv">13</span>,</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend_fontsize          =</span> <span class="dv">12</span>,</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">title_fontsize           =</span> <span class="dv">16</span>,</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">title  =</span> <span class="st">&quot;CD8 T cell differentiation: DEG modules (GSE285248)&quot;</span>,</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">file   =</span> <span class="st">&quot;cd8_module_heatmap.png&quot;</span>,</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">width  =</span> <span class="dv">10</span>,</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">height =</span> <span class="dv">12</span></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<figure>
<img src="../assets/figures/cd8_01_module_heatmap.png"
alt="CD8 T cell DEG modules" />
<figcaption aria-hidden="true">CD8 T cell DEG modules</figcaption>
</figure>
<p>Rows are split by module and ordered early-peaking to late-peaking;
columns run naive, memory, exhausted. The <code>Stability</code> bar on
the left encodes each module’s Jaccard score, and row titles carry both
module size and stability.</p>
<p>Note the two ways of choosing labels. <code>rank_table</code> +
<code>top_n_label</code> labels the top <em>n</em> genes per module by a
statistic you supply, which is usually what you want for a figure;
<code>label_features</code> labels an explicit list of genes. The two
can be combined.</p>
<h1 data-number="10" id="plot-module-trajectories"><span
class="header-section-number">10</span> Plot Module Trajectories</h1>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pattern_lineplot</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  obj, <span class="at">cluster_palette =</span> <span class="st">&quot;paired&quot;</span>, <span class="at">base_size =</span> <span class="dv">15</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">title_fontsize =</span> <span class="dv">14</span>,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># the ordering column is an integer rank, so relabel the axis with the</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># state names it stands for</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab        =</span> <span class="st">&quot;Differentiation state&quot;</span>,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">time_labels =</span> <span class="fu">c</span>(<span class="st">&quot;1&quot;</span> <span class="ot">=</span> <span class="st">&quot;TN&quot;</span>, <span class="st">&quot;2&quot;</span> <span class="ot">=</span> <span class="st">&quot;TMEM&quot;</span>, <span class="st">&quot;3&quot;</span> <span class="ot">=</span> <span class="st">&quot;TEX&quot;</span>),</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">x_angle     =</span> <span class="dv">0</span>,</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">file =</span> <span class="st">&quot;cd8_module_patterns.pdf&quot;</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<figure>
<img src="../assets/figures/cd8_03_module_patterns.png"
alt="Mean z-score trajectory per module" />
<figcaption aria-hidden="true">Mean z-score trajectory per
module</figcaption>
</figure>
<h1 data-number="11" id="check-module-coherence"><span
class="header-section-number">11</span> Check Module Coherence</h1>
<p>Clustering guarantees that a module’s genes are closer to each other
than to other modules. It does not guarantee they actually agree.
Correlating every gene in a module against every other one shows whether
the module is one programme or several averaging together.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">module_correlation_summary</span>(obj)</span></code></pre></div>
<pre><code>#&gt;     Cluster     N NShown MeanCor
#&gt; 1: Cluster1   388    388   0.876
#&gt; 2: Cluster2   776    776   0.916
#&gt; 3: Cluster3   158    158   0.829
#&gt; 4: Cluster4   243    243   0.857
#&gt; 5: Cluster5  1019   1019   0.931
#&gt; 6: Cluster6   416    416   0.886</code></pre>
<p>Every module sits between 0.83 and 0.93, so all six are internally
coherent. A value below roughly 0.3, or visible sub-blocks in the
heatmap below, would mean the module should be split by raising
<code>k</code>.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">module_correlation_heatmap</span>(</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  obj,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">clusters        =</span> <span class="st">&quot;Cluster6&quot;</span>,   <span class="co"># the exhaustion-specific module</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># every gene in the module is used by default; printing 416 row names would</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># be unreadable, so only the 30 strongest-signal genes get labelled</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">label_top_n     =</span> <span class="dv">30</span>,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">corr_palette    =</span> <span class="st">&quot;rdbu&quot;</span>,   <span class="co"># correlations diverge around 0</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">label_fontsize  =</span> <span class="dv">9</span>,</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend_fontsize =</span> <span class="dv">12</span>,</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">title_fontsize  =</span> <span class="dv">11</span>,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">file =</span> <span class="st">&quot;cd8_correlation.png&quot;</span>, <span class="at">width =</span> <span class="fl">7.5</span>, <span class="at">height =</span> <span class="dv">7</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<figure>
<img src="../assets/figures/cd8_05_module_correlation.png"
alt="Gene-gene correlation inside the exhaustion module" />
<figcaption aria-hidden="true">Gene-gene correlation inside the
exhaustion module</figcaption>
</figure>
<p>A <code>.pdf</code> destination writes one page per module
instead:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">module_correlation_heatmap</span>(obj, <span class="at">file =</span> <span class="st">&quot;cd8_module_correlations.pdf&quot;</span>)</span></code></pre></div>
<h1 data-number="12" id="export-the-tables"><span
class="header-section-number">12</span> Export The Tables</h1>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_memberships</span>(obj, <span class="at">prefix =</span> <span class="st">&quot;cd8_modules&quot;</span>)</span></code></pre></div>
<p>Writes <code>cd8_modules_memberships.txt</code> (gene to module),
<code>_centroids.txt</code> (mean trajectory per module), and
<code>_stability.txt</code>. The membership table is what you would feed
into GO or GSEA enrichment, one module at a time.</p>
<h1 data-number="13" id="add-the-cutrun-layer"><span
class="header-section-number">13</span> Add The CUT&amp;RUN Layer</h1>
<p>Now the paired-omics question: does chromatin state track these
expression modules?</p>
<p>The CUT&amp;RUN tables give peak coordinates but <strong>no gene
symbol</strong>, so peaks have to be assigned to genes first. We map
each peak to its nearest gene transcription start site, using the
coordinates already present in the RNA annotation, and keep peaks within
25 kb.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>gene_tss <span class="ot">&lt;-</span> <span class="fu">unique</span>(rna_uniq[, .(Chr,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                                <span class="at">TSS  =</span> <span class="fu">ifelse</span>(Strand <span class="sc">==</span> <span class="st">&quot;+&quot;</span>, Start, End),</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">Gene =</span> Gene.Name)])</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>map_peaks_to_nearest_gene <span class="ot">&lt;-</span> <span class="cf">function</span>(peaks, genes, <span class="at">max_dist =</span> <span class="dv">25000</span>) {</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  out <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (ch <span class="cf">in</span> <span class="fu">intersect</span>(<span class="fu">unique</span>(peaks<span class="sc">$</span>Chr), <span class="fu">unique</span>(genes<span class="sc">$</span>Chr))) {</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>    gg <span class="ot">&lt;-</span> genes[Chr <span class="sc">==</span> ch][<span class="fu">order</span>(TSS)]</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    pp <span class="ot">&lt;-</span> peaks[Chr <span class="sc">==</span> ch]</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="sc">!</span><span class="fu">nrow</span>(gg) <span class="sc">||</span> <span class="sc">!</span><span class="fu">nrow</span>(pp)) <span class="cf">next</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>    i  <span class="ot">&lt;-</span> <span class="fu">findInterval</span>(pp<span class="sc">$</span>Mid, gg<span class="sc">$</span>TSS)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>    lo <span class="ot">&lt;-</span> <span class="fu">pmax</span>(i, <span class="dv">1</span><span class="dt">L</span>); hi <span class="ot">&lt;-</span> <span class="fu">pmin</span>(i <span class="sc">+</span> <span class="dv">1</span><span class="dt">L</span>, <span class="fu">nrow</span>(gg))</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>    dlo <span class="ot">&lt;-</span> <span class="fu">abs</span>(pp<span class="sc">$</span>Mid <span class="sc">-</span> gg<span class="sc">$</span>TSS[lo]); dhi <span class="ot">&lt;-</span> <span class="fu">abs</span>(pp<span class="sc">$</span>Mid <span class="sc">-</span> gg<span class="sc">$</span>TSS[hi])</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>    pick <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(dlo <span class="sc">&lt;=</span> dhi, lo, hi)</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>    out[[<span class="fu">length</span>(out) <span class="sc">+</span> <span class="dv">1</span><span class="dt">L</span>]] <span class="ot">&lt;-</span> <span class="fu">data.table</span>(<span class="at">peakN =</span> pp<span class="sc">$</span>peakN,</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">Gene  =</span> gg<span class="sc">$</span>Gene[pick],</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">dist  =</span> <span class="fu">pmin</span>(dlo, dhi))</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rbindlist</span>(out)[dist <span class="sc">&lt;=</span> max_dist]</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p><code>dual_omics_heatmap()</code> recovers the gene from a secondary
row ID using <code>gene_of_secondary</code>, whose default is
<code>sub("^.*_", "", id)</code> — everything after the last underscore.
So we name the rows <code>peak1243_Pdcd1</code> and the default just
works.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>load_cutrun <span class="ot">&lt;-</span> <span class="cf">function</span>(path, mark) {</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  tab   <span class="ot">&lt;-</span> <span class="fu">fread</span>(path)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  scols <span class="ot">&lt;-</span> <span class="fu">grep</span>(<span class="fu">paste0</span>(<span class="st">&quot;_&quot;</span>, mark, <span class="st">&quot;_Rep&quot;</span>), <span class="fu">names</span>(tab), <span class="at">value =</span> <span class="cn">TRUE</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  pk    <span class="ot">&lt;-</span> tab[, .(peakN, Chr, <span class="at">Mid =</span> <span class="fu">as.integer</span>((Start <span class="sc">+</span> End) <span class="sc">/</span> <span class="dv">2</span>))]</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  ann   <span class="ot">&lt;-</span> <span class="fu">map_peaks_to_nearest_gene</span>(pk, gene_tss)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  tab   <span class="ot">&lt;-</span> tab[peakN <span class="sc">%in%</span> ann<span class="sc">$</span>peakN]</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  ann   <span class="ot">&lt;-</span> ann[<span class="fu">match</span>(tab<span class="sc">$</span>peakN, peakN)]</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  m     <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(tab[, ..scols])</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rownames</span>(m) <span class="ot">&lt;-</span> <span class="fu">paste0</span>(ann<span class="sc">$</span>peakN, <span class="st">&quot;_&quot;</span>, ann<span class="sc">$</span>Gene)   <span class="co"># PeakID_SYMBOL</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(<span class="at">mat =</span> <span class="fu">log2</span>(m <span class="sc">+</span> <span class="dv">1</span>), <span class="at">meta =</span> <span class="fu">make_meta</span>(scols, mark), <span class="at">ann =</span> ann)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>ac <span class="ot">&lt;-</span> <span class="fu">load_cutrun</span>(paths<span class="sc">$</span>h3k27ac, <span class="st">&quot;H3K27ac&quot;</span>)</span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(ac<span class="sc">$</span>mat)</span></code></pre></div>
<pre><code>#&gt; [1] 20879    16</code></pre>
<p>A gene can carry several peaks; <code>aggregate = "mean"</code>
averages a gene’s peaks, <code>aggregate = "top"</code> takes the single
strongest one.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>ac_obj <span class="ot">&lt;-</span> <span class="fu">longitudinal_cluster</span>(ac<span class="sc">$</span>mat, ac<span class="sc">$</span>meta,</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>                               <span class="at">sample_col =</span> <span class="st">&quot;SampleID&quot;</span>,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>                               <span class="at">time_col   =</span> <span class="st">&quot;StateOrder&quot;</span>,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                               <span class="at">k =</span> <span class="dv">4</span>, <span class="at">stability =</span> <span class="cn">FALSE</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>d_ac <span class="ot">&lt;-</span> <span class="fu">dual_omics_heatmap</span>(</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">primary        =</span> obj,        <span class="co"># RNA drives the module structure and row order</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">secondary      =</span> ac_obj,     <span class="co"># chromatin is shown in that same order</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">primary_name   =</span> <span class="st">&quot;RNA&quot;</span>,</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">secondary_name =</span> <span class="st">&quot;H3K27ac&quot;</span>,</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">aggregate      =</span> <span class="st">&quot;mean&quot;</span>,</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">label_features =</span> <span class="fu">c</span>(TEX_MARKERS, TN_MARKERS),</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">zscore_palette  =</span> <span class="st">&quot;viridis&quot;</span>,</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">cluster_palette =</span> <span class="st">&quot;paired&quot;</span>,</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_column_names  =</span> <span class="cn">FALSE</span>,</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">label_fontsize     =</span> <span class="dv">13</span>,</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">row_title_fontsize =</span> <span class="dv">13</span>,</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend_fontsize    =</span> <span class="dv">12</span>,</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">title_fontsize     =</span> <span class="dv">16</span>,</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">file =</span> <span class="st">&quot;cd8_rna_vs_h3k27ac.png&quot;</span>, <span class="at">width =</span> <span class="dv">15</span>, <span class="at">height =</span> <span class="dv">12</span></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<figure>
<img src="../assets/figures/cd8_04_rna_vs_h3k27ac.png"
alt="RNA modules with matched H3K27ac signal" />
<figcaption aria-hidden="true">RNA modules with matched H3K27ac
signal</figcaption>
</figure>
<p>The chromatin panel mirrors the expression panel block for block. The
naive-high modules carry naive-high H3K27ac; the exhaustion-high module
containing <em>Pdcd1</em>, <em>Tox</em>, and <em>Lag3</em> carries
exhaustion-high H3K27ac. The activating mark is deposited where the
genes are expressed.</p>
<p>The repressive mark behaves differently, which is the point of the
comparison:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>me3 <span class="ot">&lt;-</span> <span class="fu">load_cutrun</span>(paths<span class="sc">$</span>h3k27me3, <span class="st">&quot;H3K27me3&quot;</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>d_me3 <span class="ot">&lt;-</span> <span class="fu">dual_omics_heatmap</span>(</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">primary =</span> obj, <span class="at">secondary =</span> me3<span class="sc">$</span>mat,     <span class="co"># a raw matrix also works</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">primary_name =</span> <span class="st">&quot;RNA&quot;</span>, <span class="at">secondary_name =</span> <span class="st">&quot;H3K27me3&quot;</span>,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">label_features =</span> TEX_MARKERS,</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">file =</span> <span class="st">&quot;cd8_rna_vs_h3k27me3.png&quot;</span>, <span class="at">width =</span> <span class="dv">15</span>, <span class="at">height =</span> <span class="dv">12</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>Quantifying the contrast over the exhaustion-induced genes:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>peak_state <span class="ot">&lt;-</span> <span class="fu">setNames</span>(<span class="fu">colnames</span>(cent)[<span class="fu">apply</span>(cent, <span class="dv">1</span>, which.max)], <span class="fu">rownames</span>(cent))</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>tex_genes  <span class="ot">&lt;-</span> <span class="fu">names</span>(module_of)[peak_state[module_of] <span class="sc">==</span> <span class="st">&quot;TEX&quot;</span>]</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>delta_in <span class="ot">&lt;-</span> <span class="cf">function</span>(res, meta_tab, genes) {</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  zs   <span class="ot">&lt;-</span> res<span class="sc">$</span>z_secondary</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  keep <span class="ot">&lt;-</span> <span class="fu">intersect</span>(genes, <span class="fu">rownames</span>(zs))</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  st   <span class="ot">&lt;-</span> meta_tab<span class="sc">$</span>State[<span class="fu">match</span>(<span class="fu">colnames</span>(zs), meta_tab<span class="sc">$</span>SampleID)]</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(zs[keep, st <span class="sc">==</span> <span class="st">&quot;TEX&quot;</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">-</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mean</span>(zs[keep, st <span class="sc">==</span> <span class="st">&quot;TN&quot;</span>],  <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">H3K27ac  =</span> <span class="fu">delta_in</span>(d_ac,  ac<span class="sc">$</span>meta,  tex_genes),</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">H3K27me3 =</span> <span class="fu">delta_in</span>(d_me3, me3<span class="sc">$</span>meta, tex_genes)), <span class="dv">3</span>)</span></code></pre></div>
<pre><code>#&gt;  H3K27ac H3K27me3
#&gt;    1.350   -0.032</code></pre>
<p>The activating mark is gained at exhaustion-induced genes; the
repressive mark is flat to slightly lost. Chromatin accessibility tracks
the expression modules, which is exactly the claim the original study
makes.</p>
<h1 data-number="14" id="reproducing-everything"><span
class="header-section-number">14</span> Reproducing Everything</h1>
<p>The complete script, with 114 assertions covering data integrity,
clustering correctness, palette behaviour, marker-gene placement, and
cross-omics concordance, ships with the package:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># from the package root</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">system</span>(<span class="st">&quot;Rscript examples/validate_real_data.R&quot;</span>)</span></code></pre></div>
<p>It caches the downloads under
<code>examples/outputs/geo_cache/</code>, so re-runs are offline and
fast.</p>
<h1 data-number="15" id="adapting-this-to-your-own-data"><span
class="header-section-number">15</span> Adapting This To Your Own
Data</h1>
<p>The only project-specific parts are steps 2 to 4. Everything from
step 5 onward is generic. To reuse the workflow you need:</p>
<ol type="1">
<li>A numeric feature-by-sample matrix with feature IDs as
rownames.</li>
<li>A metadata table with a sample ID column matching the matrix
columns, and a <strong>numeric</strong> ordering column for
<code>time_col</code> (real time, or an ordinal stage as here).</li>
<li>Optionally, a <code>group_col</code> for a second factor such as
genotype or treatment arm, which splits the heatmap columns and facets
the line plot.</li>
<li>Optionally, a secondary matrix whose rownames end in
<code>_&lt;GeneSymbol&gt;</code>, or a custom
<code>gene_of_secondary</code> function.</li>
</ol>
<h1 data-number="16" id="citation"><span
class="header-section-number">16</span> Citation</h1>
<p>Cite the original study and the GEO accessions alongside
<code>ModuleViz</code>:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">citation</span>(<span class="st">&quot;ModuleViz&quot;</span>)</span></code></pre></div>
<ul>
<li>GSE285248 — RNA-seq, memory and exhausted CD8 T cells.</li>
<li>GSE285245 — CUT&amp;RUN, histone modifications in the same
cells.</li>
<li>PubMed <a
href="https://pubmed.ncbi.nlm.nih.gov/40389726/">40389726</a>.</li>
</ul>
<h1 data-number="17" id="session-information"><span
class="header-section-number">17</span> Session Information</h1>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; R version 4.1.3 (2022-03-10)</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Platform: x86_64-apple-darwin13.4.0 (64-bit)</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Running under: macOS 26.6</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Matrix products: default</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; BLAS/LAPACK: /Users/hhua/miniconda3/lib/libmkl_rt.dylib</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; locale:</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] C.UTF-8/C.UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; attached base packages:</span></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] stats     graphics  grDevices utils     datasets  methods   base     </span></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; loaded via a namespace (and not attached):</span></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [1] compiler_4.1.3  fastmap_1.1.1   cli_3.6.2       htmltools_0.5.7</span></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [5] tools_4.1.3     yaml_2.3.8      rmarkdown_2.30  knitr_1.45     </span></span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [9] digest_0.6.34   xfun_0.42       rlang_1.1.3     evaluate_1.0.5</span></span></code></pre></div>
</body>
</html>
